name: Hello World CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hello-world-docker-action:v1
      - name: Hello world action step
        id: hello
        uses: nickburrows/hello-world-docker-action@v1
        with:
          who-to-greet: '誒！酷喔'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
